# 2) Each new term in the Fibonacci sequence is generated by adding the previous two terms.
# 		By starting with 1 and 2, the first 10 terms will be:
# 		1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
# 		Find the sum of all the even-valued terms in the sequence which do not exceed four million.
#
# Answer: 4613732
# Speed: 0.026
# Notes: 

sum = 0
cur = 0
a = 0
b = 1
loop do
	cur = a + b
	a, b = b, cur
	puts cur
	break if cur >= 4_000_000
	sum += cur if (cur % 2) == 0
end

puts sum